### ISSUE TITLE
Data format has changed

### ISSUE THREAD

**Issue by robmarkcole** [duarteocarmo/interactive-dashboard-post#1]
Hi 
just a heads up, the Data format has changed and your notebook now fails to run. `get_pushshift_data(data_type="comment", q=TERM_OF_INTEREST, after=TIMEFRAME, size=1000, aggs="subreddit")` now returns a dict with a single key `data`, that contains a list of 100 elements

**Comment by duarteocarmo** [comment]
Hey @robmarkcole thanks for the report! I have updated the notebook so that it runs without problems 😄 

Have fun with the tutorial!
